// Builds apps-script/scoring.gs from src/scoring/ (the SAME code the tests and the browser run), as one plain script that
// defines the global NurtsScoring for Code.gs. Run after any change to src/scoring/ or a game's rescore.js:
//   node tools/build-scoring.mjs
import { build } from 'vite';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
const out = 'test-results/scoring-build';
await build({
  configFile: false, logLevel: 'warn',
  build: { outDir: out, emptyOutDir: true, minify: false, target: 'es2017', lib: { entry: 'src/scoring/index.js', name: 'NurtsScoring', formats: ['iife'], fileName: () => 'scoring.js' } },
});
const js = readFileSync(`${out}/scoring.js`, 'utf8');
const head = `// GENERATED by tools/build-scoring.mjs from src/scoring/ — do not edit here. Paste into the Apps Script file "scoring.gs".\n// The Nurts scoring layer (requests #28–31): L1 re-derivation, traits, learning, ethics, norms, role fit, flags, insights, validity.\n`;
writeFileSync('apps-script/scoring.gs', head + js.replace(/^var NurtsScoring\s*=/m, 'var NurtsScoring ='));
rmSync(out, { recursive: true, force: true });
console.log('apps-script/scoring.gs', Math.round((head.length + js.length) / 1024), 'KB');
